<template>
    <main data-layername="bodyContent" class="flex flex-col self-center mt-20 max-w-full mx-auto text-base font-bold leading-7 text-gray-800 rounded-none w-[768px] max-md:mt-10">
      <h1 data-layername="loremIpsumDolorSitAmet" class="self-start text-5xl tracking-tighter leading-none max-md:max-w-full max-md:text-4xl">
        Lorem ipsum dolor sit amet
      </h1>
      <p data-layername="loremIpsumDolorSitAmetConsecteturAdipiscingElitSedDoEiusmodTemporIncididuntUtLaboreEtDoloreMagnaAliquaUtEnimAdMinimVeniamQuisNostrudExercitationUllamcoLaborisNisiUtAliquipExEaCommodoConsequatDuisAuteIrureDolorInReprehenderitInVoluptateVelitEsseCillumDoloreEuFugiatNullaPariaturLoremIpsumDolorSitAmetConsecteturAdipiscingElitSedDoEiusmodTemporIncididuntUtLaboreEtDoloreMagnaAliquaNonBlanditMassaEnimNecScelerisqueViverraMaurisInAliquamSemAtRisusViverraAdipiscingAtInTellusSociisNatoquePenatibusEtMagnisDisParturientMontesRidiculusMusMaurisVitaeUltriciesLeoNequeEgestasCongueQuisqueEgestasDiamRisusInHendreritGravidaRutrumQuisqueNonSitAmetNullaFacilisiMorbiTempusIaculisUrnaLoremSedRisusUltriciesTristiqueNullaAliquetEnimVolutpatBlanditAliquamEtiamEratVelitOrciEuLobortisElementumNibhIpsumSuspendisseUltricesGravidaDictumFusceUtPlaceratOrciNullaNequeConvallisACrasSemperAuctorNequeVitaeTempusQuam" class="mt-8 text-neutral-600 max-md:max-w-full">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non blandit massa enim nec. Scelerisque viverra mauris in aliquam sem. At risus viverra adipiscing at in tellus. Sociis natoque penatibus et magnis dis parturient montes. Ridiculus mus mauris vitae ultricies leo. Neque egestas congue quisque egestas diam. Risus in hendrerit gravida rutrum quisque non. Sit amet nulla facilisi morbi tempus iaculis urna. Lorem sed risus ultricies tristique nulla aliquet enim. Volutpat blandit aliquam etiam erat velit. Orci eu lobortis elementum nibh. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Neque convallis a cras semper auctor neque vitae tempus quam.
      </p>
      <h2 data-layername="loremIpsumDolorSitAmetConsecteturAdipiscingElitSedDoEiusmodTempor" class="self-start mt-8 text-4xl tracking-tighter leading-10 max-md:max-w-full">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.
      </h2>
      <p data-layername="loremIpsumDolorSitAmetConsecteturAdipiscingElitSedDoEiusmodTemporIncididuntUtLaboreEtDoloreMagnaAliquaNonBlanditMassaEnimNecScelerisqueViverraMaurisInAliquamSemAtRisusViverraAdipiscingAtInTellusSociisNatoquePenatibusEtMagnisDisParturientMontesRidiculusMusMaurisVitaeUltriciesLeoNequeEgestasCongueQuisqueEgestasDiamRisusInHendreritGravidaRutrumQuisqueNonSitAmetNullaFacilisiMorbiTempusIaculisUrnaLoremSedRisusUltriciesTristiqueNullaAliquetEnimVolutpatBlanditAliquamEtiamEratVelitOrciEuLobortisElementumNibhIpsumSuspendisseUltricesGravidaDictumFusceUtPlaceratOrciNullaNequeConvallisACrasSemperAuctorNequeVitaeTempusQuamLoremIpsumDolorSitAmetConsecteturAdipiscingElitSedDoEiusmodTemporIncididuntUtLaboreEtDoloreMagnaAliquaNonBlanditMassaEnimNecScelerisqueViverraMaurisInAliquamSemAtRisusViverraAdipiscingAtInTellusSociisNatoquePenatibusEtMagnisDisParturientMontesRidiculusMusMaurisVitaeUltriciesLeoNequeEgestasCongueQuisqueEgestasDiamRisusInHendreritGravidaRutrumQuisqueNonSitAmetNullaFacilisiMorbiTempusIaculisUrnaLoremSedRisusUltriciesTristiqueNullaAliquetEnimVolutpatBlanditAliquamEtiamEratVelitOrciEuLobortisElementumNibhIpsumSuspendisseUltricesGravidaDictumFusceUtPlaceratOrciNullaNequeConvallisACrasSemperAuctorNequeVitaeTempusQuam" class="mt-6 text-neutral-600 max-md:max-w-full">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non blandit massa enim nec. Scelerisque viverra mauris in aliquam sem. At risus viverra adipiscing at in tellus. Sociis natoque penatibus et magnis dis parturient montes. Ridiculus mus mauris vitae ultricies leo. Neque egestas congue quisque egestas diam. Risus in hendrerit gravida rutrum quisque non. Sit amet nulla facilisi morbi tempus iaculis urna. Lorem sed risus ultricies tristique nulla aliquet enim. Volutpat blandit aliquam etiam erat velit. Orci eu lobortis elementum nibh. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Neque convallis a cras semper auctor neque vitae tempus quam.<br /><br />Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Non blandit massa enim nec. Scelerisque viverra mauris in aliquam sem. At risus viverra adipiscing at in tellus. Sociis natoque penatibus et magnis dis parturient montes. Ridiculus mus mauris vitae ultricies leo. Neque egestas congue quisque egestas diam. Risus in hendrerit gravida rutrum quisque non. Sit amet nulla facilisi morbi tempus iaculis urna. Lorem sed risus ultricies tristique nulla aliquet enim. Volutpat blandit aliquam etiam erat velit. Orci eu lobortis elementum nibh. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Neque convallis a cras semper auctor neque vitae tempus quam.
      </p>
    </main>
  </template>
  
  <script lang="ts">
  import { defineComponent } from 'vue'
  
  export default defineComponent({
    name: 'PrivacyBodyContent'
  })
  </script>